.TH SHA1SUM 1
.SH NAME
sha1sum \- compute and check SHA1 message digest
.SH SYNOPSIS
.B sha1sum
[
.I file ...
]
.SH DESCRIPTION
Sha1sum computes the 40 hex digit National Institute of 
Standards and Technology SHA1 secure hash algorithm described in
FIBS PUB 180-1. If no files are given, the standard input is summed.
